name: Links check

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  links-check:
    name: Links check
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
      - name: Links check
        uses: lycheeverse/lychee-action@v2
        with:
          args: --exclude-path README.md **/*.md